### PR TITLE
Omit path parts by regex array

### LINKED ISSUE #25: Add option to omit specific string
Example:
I have file `src/foo/index.ts`
And I want to get relative path for it from `src/bar.ts`
I want to get relative path like `./foo`

In this case, `/index.ts` is omitted

So, this extension is amazing and I'm mind to open Pull Request for this feature.

But I need to discuss usage and api for it.

May be make it array of regs?

kinda

given
`config.omit = [ /\/index.ts$/ ]`, and relative path `src/foo/index.ts`
regexp in omit config will match string: `/index.ts`.
And so I will just remove it from resulting relative path. Result will be `src/foo`

What do you think @jakob101 ?

### PR DESCRIPTION
**Pull request by ColCh**
Close #25

### CODE REVIEW

**Comment by ColCh** [comment]
How it looks like 

<details>

file

</details>

**Comment by gabrielecirulli** [comment]
I'd love to have this contribution merged, as I currently often have to manually delete `index` from the generated path

**Comment by jakob101** [comment]
I will test and publish over the weekend.

**Comment by gabrielecirulli** [comment]
Amazing, thanks!

**Pull request merged**
